### ISSUE TITLE
circle-ci: build static assets into go binary

### ISSUE THREAD

**Issue by loganmeetsworld** [buzzfeed/sso#8] opened 2018-08-22 13:04 UTC
**Is your feature request related to a problem? Please describe.**
Currently, static assets are not built into the binary.

**Describe the solution you'd like**
We can build the static assets into the go binary to make it easier to pull and use the Docker image without needing to mount the static directory.

**Comment by danbf** [comment] 2018-08-23 15:25
duplicate of https://github.com/buzzfeed/sso/issues/8

**Closed by danbf** 2018-08-23 15:25 UTC
Labels: enhancement
