### ISSUE TITLE
Loosing the connection to k8s service(s) in short  intervals

### ISSUE THREAD

**Issue by justinmydomain** [buzzfeed/sso#164] opened 2019-03-07 10:18 UTC
**Describe the bug**
SSO service fail to connect to the k8s service for a short time. This is happening in  every 10-20 Minutes intervals.  

**Expected behavior**
Connection to the service , without any interruptions through sso.

**Logs from proxy container**

$ kubectl logs -f -n sso sso-proxy-8568f5d894-xxxx | grep  "error"

{"http_status":500,"level":"info","msg":"error page","page_message":"An unexpected error occurred","page_title":"Internal Error","service":"sso-proxy","time":"2019-03-07 09:22:30.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"error loading sesion with old cookie cipher","service":"sso-proxy","time":"2019-03-07 09:22:30.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"error authenticating user","remote_address":"83.X.X.X","service":"sso-proxy","time":"2019-03-07 09:22:30.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"unknown error authenticating user","service":"sso-proxy","time":"2019-03-07 09:22:30.379"}
{"http_status":500,"level":"info","msg":"error page","page_message":"An unexpected error occurred","page_title":"Internal Error","service":"sso-proxy","time":"2019-03-07 09:22:30.379"}
{"error":"http: named cookie not present","level":"error","msg":"error authenticating user","remote_address":"83.X.X.X","service":"sso-proxy","time":"2019-03-07 09:22:30.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"error loading sesion with old cookie cipher","service":"sso-proxy","time":"2019-03-07 09:42:30.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"error authenticating user","remote_address":"83.X.X.X","service":"sso-proxy","time":"2019-03-07 09:42:30.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"unknown error authenticating user","service":"sso-proxy","time":"2019-03-07 09:42:30.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"error loading sesion with old cookie cipher","service":"sso-proxy","time":"2019-03-07 09:42:30.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"error authenticating user","remote_address":"83.X.X.X","service":"sso-proxy","time":"2019-03-07 09:42:30.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"unknown error authenticating user","service":"sso-proxy","time":"2019-03-07 09:42:30.379"}
{"http_status":500,"level":"info","msg":"error page","page_message":"An unexpected error occurred","page_title":"Internal Error","service":"sso-proxy","time":"2019-03-07 09:42:30.379"}
{"http_status":500,"level":"info","msg":"error page","page_message":"An unexpected error occurred","page_title":"Internal Error","service":"sso-proxy","time":"2019-03-07 09:42:30.379"}
{"error":"http: named cookie not present","level":"error","msg":"error authenticating user","remote_address":"83.X.X.X","service":"sso-proxy","time":"2019-03-07 09:42:30.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"error loading sesion with old cookie cipher","service":"sso-proxy","time":"2019-03-07 09:59:33.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"error authenticating user","remote_address":"83.X.X.X","service":"sso-proxy","time":"2019-03-07 09:59:33.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"unknown error authenticating user","service":"sso-proxy","time":"2019-03-07 09:59:33.379"}
{"http_status":500,"level":"info","msg":"error page","page_message":"An unexpected error occurred","page_title":"Internal Error","service":"sso-proxy","time":"2019-03-07 09:59:33.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"error loading sesion with old cookie cipher","service":"sso-proxy","time":"2019-03-07 09:59:33.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"error authenticating user","remote_address":"83.X.X.X","service":"sso-proxy","time":"2019-03-07 09:59:33.379"}
{"error":"cipher: message authentication failed","level":"error","msg":"unknown error authenticating user","service":"sso-proxy","time":"2019-03-07 09:59:33.379"}

**Desktop (please complete the following information):**
- Google k8s cluster

**Comment by benjsto** [comment] 2019-03-11 03:21
Thanks for submitting! I'm going to look into this and may follow up here with some questions about your setup.

**Comment by benjsto** [comment] 2019-03-14 14:56
I can't reproduce behavior like this in my current setup - I'm running a fairly recent version of SSO in minikube in a dev environment.

I'm not easily able to spin up a Google k8s cluster to test this there, maybe somebody else could? 

Other datapoints that may be useful are what version of SSO you saw this with, and if it's possible for you to run a more recent version and see if you still have this happening.

**Comment by justinmydomain** [comment] 2019-03-20 08:46
Thank you for the feedback! 

I have tried with the latest version (V1.1.0) , and the problem solved it seems. But it introduced a new issue with COOKIE_SECRET key value size. 
I am getting the following error: 

`"error":"Invalid configuration:\n  Invalid value for COOKIE_SECRET; must decode to 32 or 64 bytes, but decoded to 24 bytes"` 

I have managed to generate the new value with the following command,: 

$ openssl rand -base64 32 | base64

Its works for `sso-proxy` service, but not for `sso-auth` service. `sso-auth` service was complaining about new key and I had to use old version(V1.0.0)  only for sso-auth. The error with new key is as follows.

$ kubectl logs sso-auth-b4cfcb8c4-jhh4v -n sso
{"error":"siv: bad key size","level":"error","msg":"","service":"sso-authenticator","time":"2019-03-18 09:19:46.3189"}
 
So the conclusion is , sso-proxy service works with V1.1.0, and with new COOKIE_SECRET value. But sso-auth service is still working with V1.0.0.

How can I solve the issue with Key size for sso-auth?

**Comment by benjsto** [comment] 2019-03-25 21:39
`$ openssl rand -base64 32 | base64`

Looks like you're running a base64 value thru `base64` again, try it without that.

I'm going to close this issue as running on more recent version has solved it - if you continue to have a problem getting sso-auth to work, feel free to file a separate issue for that. Thanks again!

**Closed by benjsto** 2019-03-25 21:39 UTC
